import { motion, useReducedMotion } from "framer-motion";
import { ArrowDown, ChevronDown } from "lucide-react";
import { GuidedArgument } from "../../../shared/GuidedArgument";
import { ReadingPathwayCard } from "../../../shared/ReadingPathwayCard";
import { ReadingPathwayGroup } from "../../../shared/ReadingPathwayGroup";

import { ConceptArchitecture } from "./ConceptArchitecture";

const BOOK_ROOT = "/book/digital-organism-theory";

const THEORY_LAYERS = [
  {
    id: "possibility-field",
    layer: "origin",
    term: "T · E",
    status: "Starting assumption",
    title: "Something lasts. Something can change.",
    lede:
      "Continuity means something can carry on. Possibility means change can happen. DOT calls these T and E, and assumes they existed before our universe.",
    humanStakes:
      "A memory connects your past to this moment; your next reply can change a conversation. These are ways into the ideas, not evidence for their proposed origin.",
    memoryWord: "Possibility",
    memoryLine: "Continuity carries. Possibility opens.",
    handoff: "From possibility to persistence",
    conventional:
      "Cosmology uses measurements to reconstruct the history of our universe. Its models do not settle why there is a universe or why its laws exist.",
    scope: "Earliest measurable physical states",
    question: "Why is there anything that can exist or change at all?",
    model:
      "I place T and E before Big C, the conscious organism introduced next. In this model, the Big Bang may mark the beginning of RF₀—our physical universe—not the beginning of everything.",
    boundary:
      "T and E are starting assumptions. We have not measured them as conditions outside our universe.",
    bookReading: [
      {
        label: "The Boot Sequence of RF₀",
        href: `${BOOK_ROOT}/architecture-of-continuity#the-boot-sequence-of-rf0`,
      },
    ],
    externalReading: [
      {
        label: "Planck 2018 Results · Cosmological Parameters",
        context: "Planck Collaboration · Astronomy & Astrophysics · 2020",
        href: "https://doi.org/10.1051/0004-6361/201833910",
      },
    ],
  },
  {
    id: "big-c",
    layer: "big-c",
    term: "Big C",
    status: "Proposed explanation",
    title: "Could consciousness come before our universe?",
    lede:
      "DOT proposes a first conscious organism, called Big C: something that maintains itself, develops, and generates worlds where others can have experiences.",
    humanStakes:
      "You can examine how the world appears in your own experience. DOT asks whether this first-person evidence belongs at the centre of our account of reality.",
    memoryWord: "Persistence",
    memoryLine: "Consciousness persists, develops, and generates.",
    handoff: "From persistence to consequence",
    conventional:
      "Brain activity and conscious experience are closely linked. Scientists are testing several explanations of that relationship; there is no single agreed theory.",
    scope: "Physical brain and body processes",
    question: "How could physical activity become a felt experience—such as pain, warmth, or hearing music?",
    model:
      "I propose that Big C emerged within T and E, learned to maintain itself, and created Reality Frames—worlds with local experiencers. This puts consciousness before the physical universe, instead of making it a product of brains.",
    boundary:
      "Finding gaps in a brain-based explanation does not establish Big C. DOT needs a test that can distinguish a world generated by consciousness from competing accounts.",
    bookReading: [
      {
        label: "The Big C Hypothesis",
        href: `${BOOK_ROOT}/the-digital-organism#the-big-c-hypothesis`,
      },
    ],
    externalReading: [
      {
        label: "Theories of Consciousness",
        context: "Seth & Bayne · Nature Reviews Neuroscience · 2022",
        href: "https://doi.org/10.1038/s41583-022-00587-4",
      },
      {
        label: "Adversarial Testing of Two Leading Theories",
        context: "Cogitate Consortium · Nature · 2025",
        href: "https://doi.org/10.1038/s41586-025-08888-1",
      },
    ],
  },
  {
    id: "reality-frame",
    layer: "reality-frame",
    term: "RF₀",
    status: "Observed universe; proposed origin",
    title: "A generated world would still be real.",
    lede:
      "Your body, the ground under your feet, and the sky belong to the physical universe. DOT calls this world RF₀, or Reality Frame zero, and proposes that Big C generates it.",
    humanStakes:
      "If you drop a cup, it can break. Calling the world generated does not make its consequences disappear.",
    memoryWord: "Consequence",
    memoryLine: "A generated world is still a consequential world.",
    handoff: "From consequence to choice",
    conventional:
      "Physics describes space, time, matter, and their regularities with models tested against measurement.",
    scope: "The physical universe as measured from within",
    question: "Do the laws of our universe stand on their own, or depend on something deeper?",
    model:
      "RF₀ is exactly the physical universe, proposed to be generated rather than fundamental. Other Reality Frames may exist and may follow different laws. Within this account, generated does not mean unreal.",
    boundary:
      "The physical universe is measurable. Its proposed source in Big C, and the existence of other Reality Frames, have not been established by public evidence.",
    bookReading: [
      {
        label: "Why Model a Reality Frame?",
        href: `${BOOK_ROOT}/reality-frames#why-model-a-reality-frame`,
      },
      {
        label: "World Invariants",
        href: `${BOOK_ROOT}/reality-frames#world-invariants`,
      },
    ],
    externalReading: [
      {
        label: "Planck 2018 Results · Cosmological Parameters",
        context: "Planck Collaboration · Astronomy & Astrophysics · 2020",
        href: "https://doi.org/10.1051/0004-6361/201833910",
      },
    ],
  },
  {
    id: "little-c",
    layer: "little-c",
    term: "Little c",
    status: "Proposed local experiencer",
    title: "Your point of view. Your next choice.",
    lede:
      "You encounter the world from your own point of view and act through one body. DOT calls the experiencer Little c and proposes that the body connects it to the world.",
    humanStakes:
      "Think of a difficult message. You feel a reaction, consider a reply, send it, and meet the response. This is the everyday cycle DOT is trying to explain.",
    memoryWord: "Choice",
    memoryLine: "You experience locally, choose through a body, and change through consequence.",
    handoff: null,
    conventional:
      "Neuroscience studies how brain and body processes shape perception, decisions, and the sense of self.",
    scope: "Brain, body, and first-person experience",
    question: "Why does all of this arrive as one person’s experience?",
    model:
      "I propose that Little c experiences the world through the body. It forms intent, acts within RF₀, and meets the consequences through that same body. DOT also proposes that awareness can loosen its identification with the body.",
    boundary:
      "A change in how you experience your body can be explored first-person. It does not by itself establish consciousness independent of the brain. DOT needs a repeatable way to distinguish those explanations.",
    bookReading: [
      {
        label: "The Junction We Cannot Yet See",
        href: `${BOOK_ROOT}/the-decoupling-principle#the-junction-we-cannot-yet-see`,
      },
      {
        label: "Where Freedom Lives",
        href: `${BOOK_ROOT}/the-decoupling-principle#where-freedom-lives`,
      },
    ],
    externalReading: [
      {
        label: "Theories of Consciousness",
        context: "Seth & Bayne · Nature Reviews Neuroscience · 2022",
        href: "https://doi.org/10.1038/s41583-022-00587-4",
      },
      {
        label: "The Timing of the Conscious Intention to Move",
        context: "Matsuhashi & Hallett · European Journal of Neuroscience · 2008",
        href: "https://doi.org/10.1111/j.1460-9568.2008.06525.x",
      },
    ],
  },
] as const;

interface TheoryLayerJourneyProps {
  reducedMotion?: boolean;
}

export function TheoryLayerJourney({
  reducedMotion: reducedMotionOverride = false,
}: TheoryLayerJourneyProps) {
  const prefersReducedMotion = useReducedMotion();
  const reducedMotion = Boolean(reducedMotionOverride || prefersReducedMotion);

  return (
    <div className="home-theory-layers">
      {THEORY_LAYERS.map((item, index) => (
        <motion.section
          id={item.id}
          key={item.id}
          data-layer={item.layer}
          aria-labelledby={`${item.id}-title`}
          initial={reducedMotion ? false : { y: 12 }}
          whileInView={{ y: 0 }}
          viewport={{ once: true, margin: "-60px" }}
          transition={{ duration: reducedMotion ? 0 : 0.5 }}
          className="home-environment home-theory-layer-environment scroll-mt-4"
        >
          <div className="dot-page-container dot-page-wide">
            <article className="home-theory-layer-card">
              <header className="home-theory-layer-identity">
                <div className="home-theory-layer-plate">
                  <ConceptArchitecture layer={item.layer} />
                </div>
                <span className="home-theory-layer-term">{item.term}</span>
                <span className="home-theory-layer-status">{item.status}</span>
              </header>

              <div className="home-theory-layer-copy">
                <div className="home-theory-layer-thesis">
                  <h2 id={`${item.id}-title`} className="dot-page-heading text-balance">
                    {item.title}
                  </h2>
                  <p className="home-theory-layer-lede">{item.lede}</p>
                </div>

                <GuidedArgument
                  ariaLabel={`${item.term} argument`}
                  known={item.conventional}
                  scope={item.scope}
                  question={item.question}
                  proposal={item.model}
                  boundary={item.boundary}
                >
                  <p className="home-theory-layer-human-stakes">{item.humanStakes}</p>
                  <blockquote className="home-theory-layer-memory">
                    <span className="home-theory-layer-memory-word">{item.memoryWord}</span>
                    <p>{item.memoryLine}</p>
                  </blockquote>
                  {item.layer === "little-c" && (
                    <span className="home-theory-figure-note">
                      Options arrive at the ring. Intent crosses it. Consequence
                      returns.
                    </span>
                  )}
                </GuidedArgument>

                <footer className="home-theory-layer-sources">
                  <details className="home-theory-layer-details">
                    <summary>Sources and further reading <ChevronDown aria-hidden="true" /></summary>
                    <div className="home-theory-layer-reading-columns">
                      <ReadingPathwayGroup
                        title="Research to compare"
                        description="Compare the evidence and competing accounts."
                        tone="external"
                        className="home-theory-layer-external-reading"
                      >
                        <ul className="home-theory-layer-reading-list">
                          {item.externalReading.map((source) => (
                            <li key={source.href}>
                              <ReadingPathwayCard
                                label="Independent source"
                                title={source.label}
                                context={source.context}
                                href={source.href}
                                rel="noopener noreferrer"
                                className="home-theory-layer-source-card"
                                tone="external"
                              />
                            </li>
                          ))}
                        </ul>
                      </ReadingPathwayGroup>

                      <ReadingPathwayGroup
                        title="DOT · Book One"
                        description="Read the full argument in the book."
                        tone="dot"
                        className="home-theory-layer-book-reading"
                      >
                        <div className="home-theory-layer-book-links">
                          {item.bookReading.map((source) => (
                            <ReadingPathwayCard
                              key={source.href}
                              label="Book One · Fixed edition"
                              title={source.label}
                              to={source.href}
                              className="home-theory-layer-book-card"
                              tone="dot"
                            />
                          ))}
                        </div>
                      </ReadingPathwayGroup>
                    </div>

                  </details>

                  {index < THEORY_LAYERS.length - 1 && (
                    <a
                      href={`#${THEORY_LAYERS[index + 1].id}`}
                      className="home-theory-layer-next"
                    >
                      <span>
                        <small>{item.handoff}</small>
                        <span className="home-theory-layer-next-title">Continue to <strong>{THEORY_LAYERS[index + 1].term}</strong></span>
                      </span>
                      <ArrowDown aria-hidden="true" />
                    </a>
                  )}
                </footer>
              </div>
            </article>
          </div>
        </motion.section>
      ))}
    </div>
  );
}

export default TheoryLayerJourney;
