"""Add Knowledge Vault models

Revision ID: 0a354b662a63
Revises: 0003_footprint_graph
Create Date: 2026-07-04 15:31:34.147721
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0a354b662a63'
down_revision: str | None = '0003_footprint_graph'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_objects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('object_store_key', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'object_store_key', name='uq_source_object_owner_key')
    )
    op.create_index(op.f('ix_source_objects_owner_id'), 'source_objects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_source_objects_status'), 'source_objects', ['status'], unique=False)
    op.create_table('source_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_object_id', sa.String(length=64), nullable=False),
    sa.Column('version_num', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('extracted_text_ref', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_object_id'], ['source_objects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_object_id', 'version_num', name='uq_source_version_num')
    )
    op.create_index(op.f('ix_source_versions_source_object_id'), 'source_versions', ['source_object_id'], unique=False)
    op.create_index(op.f('ix_source_versions_status'), 'source_versions', ['status'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_version_id', sa.String(length=64), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_version_id'], ['source_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_version_id', 'chunk_index', name='uq_knowledge_chunk_index')
    )
    op.create_index(op.f('ix_knowledge_chunks_source_version_id'), 'knowledge_chunks', ['source_version_id'], unique=False)
    op.create_table('source_anchors',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('chunk_id', sa.String(length=64), nullable=False),
    sa.Column('anchor_type', sa.String(length=32), nullable=False),
    sa.Column('locator', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_anchors_chunk_id'), 'source_anchors', ['chunk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_anchors_chunk_id'), table_name='source_anchors')
    op.drop_table('source_anchors')
    op.drop_index(op.f('ix_knowledge_chunks_source_version_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_source_versions_status'), table_name='source_versions')
    op.drop_index(op.f('ix_source_versions_source_object_id'), table_name='source_versions')
    op.drop_table('source_versions')
    op.drop_index(op.f('ix_source_objects_status'), table_name='source_objects')
    op.drop_index(op.f('ix_source_objects_owner_id'), table_name='source_objects')
    op.drop_table('source_objects')
    # ### end Alembic commands ###
